name: Mobile App Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'native/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Setup repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup EAS
        uses: expo/expo-github-action@v9
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          cd native
          npm ci
          echo $GOOGLE_SERVICES_JSON > ./google-services.json

      - name: Build app
        run: |
          cd native
          eas build --platform android --non-interactive --no-wait --environment production